"""empty message

Revision ID: 34a25d532085
Revises: ae9e8b9280ad
Create Date: 2019-11-09 13:17:53.144872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a25d532085'
down_revision = 'ae9e8b9280ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crawls_region_name'), 'crawls', ['region_name'], unique=False)
    op.create_index(op.f('ix_crawls_region_slug'), 'crawls', ['region_slug'], unique=False)
    op.create_index(op.f('ix_crawls_site'), 'crawls', ['site'], unique=False)
    op.create_index(op.f('ix_crawls_title'), 'crawls', ['title'], unique=False)
    op.create_index(op.f('ix_crawls_transmission'), 'crawls', ['transmission'], unique=False)
    op.create_index(op.f('ix_crawls_url'), 'crawls', ['url'], unique=False)
    op.create_index(op.f('ix_crawls_user_phone'), 'crawls', ['user_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawls_user_phone'), table_name='crawls')
    op.drop_index(op.f('ix_crawls_url'), table_name='crawls')
    op.drop_index(op.f('ix_crawls_transmission'), table_name='crawls')
    op.drop_index(op.f('ix_crawls_title'), table_name='crawls')
    op.drop_index(op.f('ix_crawls_site'), table_name='crawls')
    op.drop_index(op.f('ix_crawls_region_slug'), table_name='crawls')
    op.drop_index(op.f('ix_crawls_region_name'), table_name='crawls')
    # ### end Alembic commands ###
