"""empty message

Revision ID: 8ca0ba2d239c
Revises: be7859f691bd
Create Date: 2019-11-14 19:22:22.687445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca0ba2d239c'
down_revision = 'be7859f691bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawls', sa.Column('year', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_crawls_year'), 'crawls', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawls_year'), table_name='crawls')
    op.drop_column('crawls', 'year')
    # ### end Alembic commands ###
